### ISSUE TITLE
libSass 3.1.0 compatibility

### ISSUE THREAD

**Issue by marcopompili** [craigbarnes/lua-sass#4]
Hi Craig,

I cannot build your bindings on the new version of libSass. Looks like there was a quite big change in libSass archtecture, now sass_interface.h is deprecated in favor of sass_context.h

**Comment by craigbarnes** [comment]
I just built the lua-sass bindings against libsass master and everything seems to work here (except for 1 broken assertion in `test.lua`, which I just fixed). Are you getting an error message? If so, I suspect it would be highly useful for me to know what it is :)

**Comment by marcopompili** [comment]
Hey Craig,

I built the master like this:
```
autoreconf -i
./configure
make
make install
```

/usr/local/include/sass_interface.h

is not preset so the build just fail.

Using that process of building you should recreate the error.

**Comment by craigbarnes** [comment]
Ah yes, you're right. I was building against a git checkout instead of the installed library/headers. The `sass_interface.h` header is still in the repo but doesn't get installed now for some reason. I'll take a look at updating the bindings to use `sass_context.h` when I get time.

**Comment by craigbarnes** [comment]
Ok, I've just updated to the new API. Let me know if you have any more trouble getting it to build.

**Comment by marcopompili** [comment]
Thanks Craig, now I can build the extension without a problem.

**Comment by Eroica** [comment]
libsass re-organized their headers again, and the file `sass_context.h' is now located in a sub-folder called `sass'.
(See their commit for more informations: https://github.com/sass/libsass/commit/36feef0c4ccfb77438cba99fcc33094444363054)

To reflect the upstream changes, `sass_context.h' should be changed to `sass/context.h'.

**Comment by craigbarnes** [comment]
@Eroica - I've opened a separate issue (#5) for libsass 3.3.x compatibility.
